Iter13
mi4r/go-url-shortener pull request #13
Opened 2024-08-13 17:21 UTC by mi4r

2024-08-16 14:41 UTC, tmvrus requested changes
Работа хорошая, но надо бы поправить мелочевку

2024-08-16 14:41 UTC, tmvrus commented on internal/storage/db_storage.go
> +	fmt.Println("1")
ай ай

2024-08-16 14:41 UTC, tmvrus commented on internal/storage/db_storage.go
> +	fmt.Println("2")
ой ой

2024-08-16 14:41 UTC, tmvrus commented on internal/storage/db_storage.go
> +	fmt.Println("3")
ну ок

2024-08-16 14:41 UTC, tmvrus commented on internal/storage/db_storage.go
> +// }
в готовом проекте не должно быть закоменченного кода, это замусоривает проект и усложняет чтение

2024-08-16 15:40 UTC, mi4r commented on internal/storage/db_storage.go
> +// }
Такой оффтоп вопрос: а вот у меня main ветка падает на моменте прохождения branchtest, это нормально?

2024-08-16 16:09 UTC, tmvrus commented on internal/storage/db_storage.go
> +// }
нет конечно

2024-08-16 16:22 UTC, mi4r commented on internal/storage/db_storage.go
> +// }
<img width="1428" alt="Снимок экрана 2024-08-16 в 19 20 57" src="https://github.com/user-attachments/assets/c4a6017a-9ea2-4f06-a479-3625ce5f5590">

2024-08-16 16:22 UTC, mi4r commented on internal/storage/db_storage.go
> +// }
Пишет, что по паттерну не подходит

2024-08-18 20:31 UTC, tmvrus commented on internal/storage/db_storage.go
> +// }
дай ссылку на джобу, я накину авторам тестов

2024-08-18 20:31 UTC, tmvrus approved these changes

2024-08-19 10:58 UTC, mi4r commented on internal/storage/db_storage.go
> +// }
https://github.com/mi4r/go-url-shortener/actions/runs/10196060124/job/28206030638

2024-08-23 11:49 UTC, merged